import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../lib/firebase_options.dart';
import '../lib/models/user.dart';

Future<void> main() async {
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Test user data
  final testUser = UserModel(
    uid: 'test_admin_001', // This will be generated by Firebase Auth
    phoneNumber: '+919000012025',
    name: 'Test Admin',
    email: 'admin@durgaapp.local',
    role: UserRole.admin,
    isActive: true,
    createdAt: DateTime.now(),
    lastLogin: DateTime.now(),
  );

  try {
    // Create user document in Firestore
    await FirebaseFirestore.instance
        .collection('users')
        .doc('test_admin_001')
        .set(testUser.toMap());

    print('✅ Test admin user added successfully!');
    print('📱 Phone: +919000012025');
    print('🔑 Password: 123456');
    print('👤 Role: Admin');
    print('');
    print('📋 Login Instructions:');
    print('1. Run the app');
    print('2. Go to Sign In');
    print('3. Enter phone: 9000012025');
    print('4. Enter password: 123456');
    print('5. Access admin dashboard at /admin');

  } catch (e) {
    print('❌ Error adding test user: $e');

    // Try to create a user with email/password authentication
    print('🔄 Attempting to create user with email/password...');

    try {
      // This would normally be done through the app's auth flow
      print('📝 To create the test user:');
      print('1. Run the app');
      print('2. Sign up with phone: 9000012025, password: 123456');
      print('3. Then manually update the user role in Firestore to "admin"');
    } catch (authError) {
      print('❌ Auth error: $authError');
    }
  }
}
